
WAAM = "wire arc additive manufacturing"
AM = "additive manufacturing"
3dcp = "extrusion 3d concrete printing"
sc3dp = "shotcrete 3d printing"
se3dp = "shot-earth 3d printing"
OS = "open-source"
AE = "http://aectual.com"


[url]
mx = "https://mx3d.com"
vertico = "http://vertico.xyz"
terre = "http://terrestrial.construction"
adaxis = "https://adaxis.eu"
hpa = "https://www.youtube.com/watch?v=y_N5xbaIY2k"
compas = "https://github.com/compas-dev"
compasfab = "https://compas.dev/compas_fab/latest/"
compas_assoc = "https://www.linkedin.com/company/compas-association/"
ch_mesh = "https://www.mesh.ch"
ch_os_constr = "https://opensource.construction"
ch_vyzn = "https://www.vyzn.tech"
ib_phoenix = "https://iconbuild.com/robotics"
titomic = "https://titomic.com/technology/?utm_source=Google&utm_medium=cpc&utm_campaign=&gad_source=1&gbraid=0AAAAAo4SvAuQ3OVuD0jLD2UFiSUoi5OD4&gclid=CjwKCAjwlbu2BhA3EiwA3yXyu06b4GmuHoj2grmZIArzZphdJkhn1Lek9o-Xo1VexsYB6oEwQKRCfBoCH_gQAvD_BwE"
odico = ""
pythonocc = "https://github.com/tpaviot/pythonocc-core"
rosindu = "https://rosindustrial.org"
cead = "https://ceadgroup.com"
aibuild = "https://ai-build.com"

[email]
gijs = "gijs@mx3d.com"
volker = "volker.ruitinga@vertico.xyz"
jelle = "jelle@terrestrial.construction"

[jelle]

opus = "https://www.zaha-hadid.com/architecture/opus/"
phd_thesis = "https://research.tudelft.nl/en/publications/architectural-robotics-bridging-the-divide-between-academic-resea"
RG = "https://www.researchgate.net/profile/Jelle-Feringa"
FH = "https://architectenweb.nl/nieuws/artikel.aspx?ID=43507"
CC = "https://blog.aectual.com/circular-canopy-for-dutch-house-of-representatives-by-zecc"
sgs = "https://www.sgssearch.nl/diensten/lca-van-product-en-dienst/lca-levenscyclusanalyse-van-product-en-dienst.html"
HS = "https://www.degroteverbinding.be/nl/projecten/ringpark-schijn/over"

[michiel]

FC = "https://www.fibercore-europe.com/en/"
