
WAAM = "wire arc additive manufacturing"
AM = "additive manufacturing"
3dcp = "extrusion 3d concrete printing"
sc3dp = "shotcrete 3d printing"



[email]
gijs = "gijs@mx3d.com"
volker = "volker.ruitinga@vertico.xyz"


